### ISSUE TITLE
BUILD FAILED 

### ISSUE THREAD

**Issue by okita-haruru** [coinbase/waas-sdk-react-native#47]
I tried to run the android example and failed to build. Here is the error code.

BUILD FAILED in 1s
    at makeError (D:\codes\waas-sdk-react-native\node_modules\execa\index.js:174:9)
    at D:\codes\waas-sdk-react-native\node_modules\execa\index.js:278:16
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async runOnAllDevices (D:\codes\waas-sdk-react-native\node_modules\@react-native-community\cli-platform-android\build\commands\runAndroid\runOnAllDevices.js:82:7)
    at async Command.handleAction (D:\codes\waas-sdk-react-native\node_modules\@react-native- community\cli\build\index.js:108:9)
info Run CLI with --verbose flag for more details.
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

My develop OS is windows 10

go version
`go version go1.18.1 windows/amd64`

node version 
`Welcome to Node.js v18.16.1.`

yarn version
`yarn install v1.22.18`

How to fix the error. Thanks.

**Comment by okita-haruru** [comment]
It fixed automaticly after I tried to build for several times. I didn't change any of the env or the code. Now it works well. Thanks for your reply!

**Comment by jbrower95** [comment]
Sure thing, reach back out if you have any questions!
